### ISSUE TITLE
Will it work if client websites are hosted at different domains? 

### ISSUE THREAD

**Issue by adoprog** [SChervonyi/SSO#1]
Please make sure it supports this scenario.

**Comment by SChervonyi** [comment]
I know common theory how it should be done. And of course I found articles like this: http://www.codeproject.com/Articles/114484/Single-Sign-On-SSO-for-cross-domain-ASP-NET-appl
But I don't have experience with mvc to just rewrite that example. I mean it would take a couple full days to a few learn about mvc (I didn't write example on forms because it wold be huge copy-paste).
So as I see I should learn more about asp.net before to make a try to get asp.net developer position.
